/**
 * @author AW
 * @flow
 */
 
const images = {
    KyKet: require('../../Assets/images/KyKet.png'),
    Logo: require('../../Assets/images/Logo.png'),
    LogoSidoc: require('../../Assets/images/LogoSidoc.png'),
    Onboard: require('../../Assets/images/Onboard.png'),
    QuanLy: require('../../Assets/images/QuanLy.png'),
    Sidoc: require('../../Assets/images/Sidoc.png'),
    SoanThao: require('../../Assets/images/SoanThao.png'),
    Stoke: require('../../Assets/images/Stoke.png'),
    ThuongThao: require('../../Assets/images/ThuongThao.png'),
    TichHop: require('../../Assets/images/TichHop.png'),
    Welcome: require('../../Assets/images/Welcome.png'),
    arrow_left: require('../../Assets/images/arrow-left.png'),
    arrow_right: require('../../Assets/images/arrow-right.png'),
    bell: require('../../Assets/images/bell.png'),
    change_password: require('../../Assets/images/change_password.png'),
    check: require('../../Assets/images/check.png'),
    help: require('../../Assets/images/help.png'),
    img_approved: require('../../Assets/images/img_approved.png'),
    img_can_approved: require('../../Assets/images/img_can_approved.png'),
    img_internet: require('../../Assets/images/img_internet.png'),
    img_logo_sidoc: require('../../Assets/images/img_logo_sidoc.png'),
    img_nointernet: require('../../Assets/images/img_nointernet.png'),
    img_rejected: require('../../Assets/images/img_rejected.png'),
    info: require('../../Assets/images/info.png'),
    language: require('../../Assets/images/language.png'),
    logout: require('../../Assets/images/logout.png'),
    maskExpire: require('../../Assets/images/maskExpire.png'),
    maskManage: require('../../Assets/images/maskManage.png'),
    maskNegotiation: require('../../Assets/images/maskNegotiation.png'),
    maskThuongThao: require('../../Assets/images/maskThuongThao.png'),
    nocheck: require('../../Assets/images/nocheck.png'),
    note: require('../../Assets/images/note.png'),
    notification: require('../../Assets/images/notification.png'),
    policy: require('../../Assets/images/policy.png'),
    search: require('../../Assets/images/search.png'),
    slider: require('../../Assets/images/slider.png'),
    success_img: require('../../Assets/images/success_img.png'),
    toggleOff: require('../../Assets/images/toggleOff.png'),
    toggleOn: require('../../Assets/images/toggleOn.png'),
    trash: require('../../Assets/images/trash.png'),
    version: require('../../Assets/images/version.png'),
    welcome_reco: require('../../Assets/images/welcome_reco.png'),
};
export default images;
