export  const ListNoti = {
    INITIALS_DONE_DOCUMENT_OTHER_USER : 'INITIALS_DONE_DOCUMENT_OTHER_USER',
    INITIALS_DOCUMENT_OTHER_USER : 'INITIALS_DOCUMENT_OTHER_USER',
    INITIALS_DOCUMENT_USER : 'INITIALS_DOCUMENT_USER',
    SIGN_DOCUMENT_USER: 'SIGN_DOCUMENT_USER',
    SIGN_DONE_DOCUMENT_USER : 'SIGN_DONE_DOCUMENT_USER',
    SIGN_DONE_DOCUMENT_OTHER_USER : 'SIGN_DONE_DOCUMENT_OTHER_USER',
    SIGN_DOCUMENT_OTHER_USER :'SIGN_DOCUMENT_OTHER_USER',
    REJECT_INITIALS_USER : 'REJECT_INITIALS_USER',
    REJECT_INITIALS_OTHER_USER : 'REJECT_INITIALS_OTHER_USER',
    REJECT_SIGN_USER : 'REJECT_SIGN_USER',
    INITIALS_DONE_DOCUMENT_USER : 'INITIALS_DONE_DOCUMENT_USER',
    REJECT_SIGN_OTHER_USER : 'REJECT_SIGN_OTHER_USER'
};
